<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aboutPhiraka_Title</name>
   <tag></tag>
   <elementGuidId>2c60d581-d319-448f-ba00-9940a13035d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-24489']/div/div/div/section[2]/div[3]/div[2]/div/section/div/div/div/div/div/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.section-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Wujudkan Potensi Masa Depan Digital Anda&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>3a454652-1da3-498c-896b-53610e348ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-title</value>
      <webElementGuid>1e29edc1-1565-411f-8815-c5cea3a3f664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wujudkan Potensi Masa Depan Digital Anda</value>
      <webElementGuid>1b91975c-50c6-4512-abf6-92bd7bcdf16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-24489&quot;)/div[@class=&quot;post-inner&quot;]/div[@class=&quot;entry-content&quot;]/div[@class=&quot;elementor elementor-24489&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-4e14a27 elementor-section-stretched elementor-section-boxed elementor-section-height-default elementor-section-height-default float-parallax-started&quot;]/div[@class=&quot;elementor-container elementor-column-gap-extended&quot;]/div[@class=&quot;elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-5cf373d animated fadeInUp&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/section[@class=&quot;elementor-section elementor-inner-section elementor-element elementor-element-6928140 elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-inner-column elementor-element elementor-element-4ab3e8f&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-e0e8658 cea-align-left elementor-widget elementor-widget-ceasectiontitle&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;section-title-wrapper&quot;]/div[@class=&quot;title-wrap&quot;]/h2[@class=&quot;section-title&quot;]</value>
      <webElementGuid>51dd7797-bff6-4738-b9fc-eff39068dd1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-24489']/div/div/div/section[2]/div[3]/div[2]/div/section/div/div/div/div/div/div/div/h2</value>
      <webElementGuid>af7bda0c-c812-43e0-9959-f903a5af7d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengenai Phiraka'])[1]/following::h2[1]</value>
      <webElementGuid>1fdfc353-9d1b-4e88-8fa3-dd8c49d5cea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your central Hub for seamless data management in talent improvement excellence.'])[1]/following::h2[1]</value>
      <webElementGuid>53c8ad68-37ed-4370-98bc-8170efd0fad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='about us'])[1]/preceding::h2[1]</value>
      <webElementGuid>01801c8d-faed-4821-8b79-f6f52dc84d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengapa Memilih Phiraka?'])[1]/preceding::h2[2]</value>
      <webElementGuid>04809bd2-4d11-4670-9017-f381ea7310d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wujudkan Potensi Masa Depan Digital Anda']/parent::*</value>
      <webElementGuid>4fab569b-41ee-426f-96c7-c2fd97d2123f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>f5edee82-23aa-443e-bf0d-975cc0f1c65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Wujudkan Potensi Masa Depan Digital Anda' or . = 'Wujudkan Potensi Masa Depan Digital Anda')]</value>
      <webElementGuid>ed9adbf3-923b-4753-bfc4-5f925c7cf163</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
