<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aboutPhiraka_Image</name>
   <tag></tag>
   <elementGuidId>a68d3e00-4ea1-4eae-817d-8e5334841605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-24489']/div/div/div/section[2]/div[3]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-full.size-full.wp-image-34703</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.attachment-full >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bf087b9b-fb6a-4a47-b959-4e24bd7d0bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>5498c4ec-651a-48df-9622-42ca55ad96cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>32bf520c-f2f0-403c-ac87-70bfe14998fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>813</value>
      <webElementGuid>984dbe4d-847a-494a-8d59-4a0d05f54b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>922</value>
      <webElementGuid>8673b297-36fa-4820-a245-9ca2fef8a4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://phiraka.com/wp-content/uploads/2024/01/Group-34552.png</value>
      <webElementGuid>44622091-3973-445a-8e86-4521587f720d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-full size-full wp-image-34703</value>
      <webElementGuid>3043b58b-95ae-4511-ae26-5a39cf71b967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://phiraka.com/wp-content/uploads/2024/01/Group-34552.png 813w, https://phiraka.com/wp-content/uploads/2024/01/Group-34552-768x871.png 768w</value>
      <webElementGuid>dfbf0314-ae61-48a6-834c-f13994072e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 813px) 100vw, 813px</value>
      <webElementGuid>d4087459-fbea-4ab4-96f3-843074abb4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-24489&quot;)/div[@class=&quot;post-inner&quot;]/div[@class=&quot;entry-content&quot;]/div[@class=&quot;elementor elementor-24489&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-4e14a27 elementor-section-stretched elementor-section-boxed elementor-section-height-default elementor-section-height-default float-parallax-started&quot;]/div[@class=&quot;elementor-container elementor-column-gap-extended&quot;]/div[@class=&quot;elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-34a2958 animated fadeInUp&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-5c6f804 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-full size-full wp-image-34703&quot;]</value>
      <webElementGuid>3496dc6d-82df-4df2-afd7-ebff3cca4e61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-24489']/div/div/div/section[2]/div[3]/div/div/div/div/img</value>
      <webElementGuid>2d38682c-155d-46aa-822f-5a76ad9c3691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://phiraka.com/wp-content/uploads/2024/01/Group-34552.png')]</value>
      <webElementGuid>b587a08c-9cbf-43b2-bbdf-b0f9083ee2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/img</value>
      <webElementGuid>a8836a94-b772-4f31-948f-53fce26a0ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://phiraka.com/wp-content/uploads/2024/01/Group-34552.png']</value>
      <webElementGuid>653cc41e-de84-4038-8ac8-cfdffddc20d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
