<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Point1_PhiroGo_Icon</name>
   <tag></tag>
   <elementGuidId>430e71cd-c16d-4b8e-8899-9b5770550655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='tabs-1']/div[2]/div/div/div[2]/div/div/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi-check-circle-fill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tabs-1 i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>16ab6938-b66e-49cf-be99-7c07543f417e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c55f1a51-02da-4c09-ba14-450a261f7251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> bi-check-circle-fill</value>
      <webElementGuid>02d556c3-acae-4ecb-bbe8-847da23c42bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-1&quot;)/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-99416aa&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-c18272d cea-view-default elementor-widget elementor-widget-ceafeaturebox&quot;]/div[@class=&quot;elementor-widget-container feature-box-wrapper feature-box-default&quot;]/div[@class=&quot;media&quot;]/div[@class=&quot;media-icon-part align-self-center&quot;]/div[@class=&quot;cea-featured-icon&quot;]/i[@class=&quot;bi-check-circle-fill&quot;]</value>
      <webElementGuid>14d9c53f-07ac-4349-9137-131cd9f3fda1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='tabs-1']/div[2]/div/div/div[2]/div/div/div/div/i</value>
      <webElementGuid>eed099ec-340b-42bd-be7b-b8896f2125a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/i</value>
      <webElementGuid>8603509c-b290-40f3-8395-b6f2c0390a29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
