<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_PhiroGo</name>
   <tag></tag>
   <elementGuidId>09cbc12c-a977-4492-b27e-c678d401162d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='tabs-1']/div[2]/div/div/div/div/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.elementor-element.elementor-element-3621050.cea-align-left.elementor-widget.elementor-widget-ceasectiontitle > div.elementor-widget-container > div.section-title-wrapper > div.section-description > p.section-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;We make it easy for you to manage day to day HR routines&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c3eb4611-7370-4a75-a329-91f5b3fb1160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-content</value>
      <webElementGuid>3d7b88a9-676b-48ca-b00f-ee952e4c728c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We make it easy for you to manage day to day HR routines</value>
      <webElementGuid>5afbe09b-2838-4f7e-b308-40737cafc887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-1&quot;)/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-99416aa&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-3621050 cea-align-left elementor-widget elementor-widget-ceasectiontitle&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;section-title-wrapper&quot;]/div[@class=&quot;section-description&quot;]/p[@class=&quot;section-content&quot;]</value>
      <webElementGuid>6006e530-ab58-423a-9e29-b2a4a3dbb8c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='tabs-1']/div[2]/div/div/div/div/div/div[2]/p</value>
      <webElementGuid>a8d1c18f-4eac-4a58-a7f7-5af641c3b10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digitize Every HR Process, Enhance Efficiency'])[1]/following::p[1]</value>
      <webElementGuid>3ad32d13-6e60-4b10-8ee7-5f9a731346d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phiro Class'])[2]/following::p[1]</value>
      <webElementGuid>365c1f8b-e314-4647-bf60-293e8ce6aa9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage employee absenteeism'])[1]/preceding::p[1]</value>
      <webElementGuid>9d4c3b69-4581-413a-a745-d22271ceb7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee self service submission'])[1]/preceding::p[1]</value>
      <webElementGuid>781a6134-92c4-4156-8bb6-27aee9f31a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='We make it easy for you to manage day to day HR routines']/parent::*</value>
      <webElementGuid>020f2c3b-6aea-4d52-a8f5-b3e0a7a0415b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/section/div[2]/div/div/div/div/div/div[2]/p</value>
      <webElementGuid>b64efafc-b75f-42da-b3f8-4c9ec2efb47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'We make it easy for you to manage day to day HR routines' or . = 'We make it easy for you to manage day to day HR routines')]</value>
      <webElementGuid>5e351e50-f406-457c-8893-0b8a39f7ff37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
